sudo: required

services:
  - docker

language: bash

script:
  # build amd64 images
  - docker build -t cwmr/pgsql-s3-backup:amd64 -f pgsql-s3-backup/Dockerfile pgsql-s3-backup
  - docker build -t cwmr/pgsql-s3-restore:amd64 -f pgsql-s3-restore/Dockerfile pgsql-s3-restore
  # build armhf images
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build --build-arg ARCH=arm -t cwmr/pgsql-s3-backup:arm -f pgsql-s3-backup/Dockerfile pgsql-s3-backup
  - docker build --build-arg ARCH=arm -t cwmr/pgsql-s3-restore:arm -f pgsql-s3-restore/Dockerfile pgsql-s3-restore
  # push images
  - wget -O manifest-tool https://github.com/estesp/manifest-tool/releases/download/v0.9.0/manifest-tool-linux-amd64
  - chmod +x ./manifest-tool
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - >
    if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      docker push cwmr/pgsql-s3-backup:amd64
      docker push cwmr/pgsql-s3-backup:arm
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm --template cwmr/pgsql-s3-backup:ARCH --target cwmr/pgsql-s3-backup:latest
      docker push cwmr/pgsql-s3-restore:amd64
      docker push cwmr/pgsql-s3-restore:arm
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm --template cwmr/pgsql-s3-restore:ARCH --target cwmr/pgsql-s3-restore:latest
    elif [ -z "$TRAVIS_TAG" ]; then
      docker tag cwmr/pgsql-s3-backup:amd64 cwmr/pgsql-s3-backup:dev-amd64
      docker tag cwmr/pgsql-s3-backup:arm cwmr/pgsql-s3-backup:dev-arm
      docker push cwmr/pgsql-s3-backup:dev-amd64
      docker push cwmr/pgsql-s3-backup:dev-arm
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm --template cwmr/pgsql-s3-backup:dev-ARCH --target cwmr/pgsql-s3-backup:dev
      docker tag cwmr/pgsql-s3-restore:amd64 cwmr/pgsql-s3-restore:dev-amd64
      docker tag cwmr/pgsql-s3-restore:arm cwmr/pgsql-s3-restore:dev-arm
      docker push cwmr/pgsql-s3-restore:dev-amd64
      docker push cwmr/pgsql-s3-restore:dev-arm
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm --template cwmr/pgsql-s3-restore:dev-ARCH --target cwmr/pgsql-s3-restore:dev
    else
      docker tag cwmr/pgsql-s3-backup:amd64 cwmr/pgsql-s3-backup:$TRAVIS_TAG-amd64
      docker tag cwmr/pgsql-s3-backup:arm cwmr/pgsql-s3-backup:$TRAVIS_TAG-arm
      docker push cwmr/pgsql-s3-backup:$TRAVIS_TAG-amd64
      docker push cwmr/pgsql-s3-backup:$TRAVIS_TAG-arm
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm --template cwmr/pgsql-s3-backup:$TRAVIS_TAG-ARCH --target cwmr/pgsql-s3-backup:$TRAVIS_TAG
      docker tag cwmr/pgsql-s3-restore:amd64 cwmr/pgsql-s3-restore:$TRAVIS_TAG-amd64
      docker tag cwmr/pgsql-s3-restore:arm cwmr/pgsql-s3-restore:$TRAVIS_TAG-arm
      docker push cwmr/pgsql-s3-restore:$TRAVIS_TAG-amd64
      docker push cwmr/pgsql-s3-restore:$TRAVIS_TAG-arm
      ./manifest-tool push from-args --platforms linux/amd64,linux/arm --template cwmr/pgsql-s3-restore:$TRAVIS_TAG-ARCH --target cwmr/pgsql-s3-restore:$TRAVIS_TAG
    fi
